# Generated by Django 4.2.30 on 2026-07-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_repair_dataset_metadata_columns'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evaluationitemresult',
            new_name='catalog_eva_run_id_6ced86_idx',
            old_name='catalog_eva_run_id_fed8de_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluationitemresult',
            new_name='catalog_eva_result__8b5181_idx',
            old_name='catalog_eva_result__45eea1_idx',
        ),
        migrations.AlterField(
            model_name='llmmodel',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic')], max_length=32),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic')], max_length=32),
        ),
    ]
