# Generated by Django 4.2.30 on 2026-07-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_generated_dataset_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmmodel',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic'), ('vllm', 'vLLM')], max_length=32),
        ),
        migrations.AlterField(
            model_name='providercredential',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('openai', 'OpenAI'), ('gemini', 'Gemini'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic'), ('vllm', 'vLLM')], max_length=32),
        ),
    ]
