# Generated by Django 4.2.30 on 2026-07-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_llmmodel_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationdataset',
            name='service_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_datasets', to='catalog.servicefeature'),
        ),
        migrations.CreateModel(
            name='EvaluationDatasetSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy_ratio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seed', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('questions_payload', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='catalog.evaluationdataset')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_snapshot', to='catalog.evaluationrun')),
                ('service_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dataset_snapshots', to='catalog.servicefeature')),
            ],
        ),
    ]
