# Generated by Django 4.2.30 on 2026-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_evaluationdataset_service_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationitemresult',
            name='ttft_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='kv_cache_usage_avg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='kv_cache_usage_max',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='kv_cache_usage_min',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='system_throughput_tps',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='throughput_p50_tps',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='throughput_p95_tps',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='tpot_p50_ms',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='tpot_p95_ms',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='ttft_p50_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='ttft_p95_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
