# Generated by Django 4.2.30 on 2026-07-19 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_evaluationitemresult_ttft_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationitemresult',
            name='router_output',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='candidate_label',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='result_type',
            field=models.CharField(choices=[('single_model', 'Single Model'), ('routing', 'Routing')], default='single_model', max_length=32),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='routing_model_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='evaluationitemresult',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_item_results', to='catalog.llmmodel'),
        ),
        migrations.AlterField(
            model_name='evaluationresult',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_results', to='catalog.llmmodel'),
        ),
        migrations.CreateModel(
            name='EvaluationRoutingCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routing_prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('large_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.llmmodel')),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routing_config', to='catalog.evaluationresult')),
                ('small_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.llmmodel')),
            ],
        ),
    ]
