# Generated by Django 4.2.30 on 2026-07-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_evaluationitemresult_router_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationdataset',
            name='service_feature',
        ),
        migrations.RemoveField(
            model_name='evaluationdatasetsnapshot',
            name='service_feature',
        ),
    ]
