# Generated by Django 4.2.30 on 2026-07-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0036_evaluationdatasetsnapshot_easy_dataset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationresult',
            name='router_latency_p50_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='router_latency_p95_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
